### ISSUE TITLE
Feature: Swap output$site_metadata_list with new data model

### ISSUE THREAD

**Issue by taylorrodgers** [Gilead-BioStats/gsm.app#173]
## Feature Details
We want to swap out the previous `tagList` produced by `site_details_meta_data_list` with the new data model.

We'd also like to move any calculations or data manipulation (previously performed by reactive functions) to be performed inside `site_details_meta_data_list`.

We'd like to display the following fields: 
- InvestigatorLastName
- InvestigatorFirstName
- Status
- City
- State
- Country
- ParticipantCount
- \# of screened participants (use name as defined in Param)
- \# of eligible participants (use name as defined in Param)
- \# of ineligible participants (use name as defined in Param)
- \# of active participants (use name as defined in Param)
- \# of completed participants (use name as defined in Param)
- \# of discontinued participants (use name as defined in Param)

We'd like the participant counts to be a nested list, similar to the previous output. (See below code for references)

This is waiting on https://github.com/Gilead-BioStats/gsm/issues/1773

## Previous Code
Just for reference, this is how this tagList was produced previously.
```
### Participant Status Functions

participant_list <- reactive({
  list(
    screened = list(
      eligible = sum(dfSUBJ()$data$enrollyn == "Y"),
      ineligible = sum(dfSUBJ()$data$enrollyn == "N")
    ),
    enrolled = list(
      completed = sum(dfSTUDCOMP()$data$compyn == "Y"),
      discontinued = sum(dfSTUDCOMP()$data$compyn == "N"),
      active = sum(!c(dfSTUDCOMP()$data$compyn %in% c("Y", "N")))
    ),
    discontinued_reasons = dfSTUDCOMP()$data$compreas
  )
})


    # ---- site data
    site_metadata <- reactive({
      shiny::req(site())

      mapping <- snapshot$lInputs$lMapping$dfSITE
      data <- snapshot$lInputs$lMeta$meta_site %>%
        dplyr::filter(
          .data[[mapping$strSiteCol]] == site()
        )

      return(data)
    })

    output$site_metadata_list <- renderUI({
      enrolled_subjects <- dfSUBJ()$data %>%
        dplyr::filter(.data$enrollyn == "Y") %>%
        dplyr::select("subjid")
      enrolled_subjects <- enrolled_subjects$subjid

      site_details_meta_data_list(site_metadata(), enrolled_subjects = enrolled_subjects, participant_list = participant_list())
    })
````

## Notes

Side note: might also be good to rename `site_details_meta_data_list` (as well as any other tagList producting functions) to `tags_[functionname]`.

**Comment by taylorrodgers** [comment]
We plan to simply use whatever is available in dfGroups. This will change the solution describe above

**Comment by jonthegeek** [comment]
Use data from https://github.com/Gilead-BioStats/gsm/issues/1790

**Comment by taylorrodgers** [comment]
Hey @jonthegeek, regarding the PR you mentioned, does this also fulfill https://github.com/Gilead-BioStats/gsm/issues/1773?

#1773 had evolved slightly from the initial description, but the issue as I recalled was that we were missing many of the metadata points below in `dfGroups`.

![image](https://github.com/user-attachments/assets/48ebbcf1-9e20-4947-b50d-12b80eba0f50)

**Comment by jonthegeek** [comment]
@taylorrodgers It does *not* address that; 1790 is just about adding pretty names (`Labels`) for use in reports (and by us). It doesn't impact the underlying data that's available. Let's continue on with the "use whatever data is available" plan. We'll sort out later whether any of this results in sub-bullets (short term everything will be at the same indentation level).

**Comment by taylorrodgers** [comment]
Per conversation on teams, we will simply use the "whatever data is available" plan :)
