### ISSUE TITLE
Feature: Participant Domain 2.0

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.app#180]
## Feature Details
Participant Details / Participant Domain table for 2.0 data.

**Comment by taylorrodgers** [comment]
For reference. These requirements may have evolved. When defaulted to "hide", we only show a select few columns. "Show" shows all columns for that particular metric.
![image](https://github.com/user-attachments/assets/596d25b9-048c-450b-ac57-3fcfd05621fe)

**Comment by samussiah** [comment]
Good point - we're most likely only working with `Mapped_*` data going forward which contain an explicit list of columns.  So for data listings this module should just display all columns.

**Comment by taylorrodgers** [comment]
> Good point - we're most likely only working with `Mapped_*` data going forward which contain an explicit list of columns. So for data listings this module should just display all columns.

Good to know! Thanks for commenting.

**Comment by jonthegeek** [comment]
Use `gsm::MakeParamLabelsList()` to make the column names in these tables.
