### ISSUE TITLE
QC: Update shinyapps.io link in readme. 

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm.app#181]

**Comment by jonthegeek** [comment]
I suspect this is related to #147. The URL is up-to-date here: https://gilead-biostats.github.io/gsm.app/dev/

I think the easiest thing to do to fix the prod version of the site will be to somewhat hack it in on the main branch. Let me see if I can do that as straightforwardly as I think...

**Comment by jonthegeek** [comment]
Oops, it ISN'T right in dev. Fixing both ways.
