### ISSUE TITLE
Bugfix: Metric Details' analysis output table does not remain highlighted

### ISSUE THREAD

**Issue by taylorrodgers** [Gilead-BioStats/gsm.app#187]
## Expected Behavior
A row on the analysis output table should remain highlighted if the site selector is anything other than "None".

## Current Behavior
Whenever a row is highlighted and the user moves to another tab on the Metric Details page, the table re-renders and removes the highlight classes in favor of the `table-striped` class.

See video here:

https://github.com/user-attachments/assets/d97acae8-6ecd-491b-ad0a-a12b806f5cd2

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jonthegeek** [comment]
My current thought on this is to get the raw data via https://github.com/Gilead-BioStats/gsm/issues/1835, and then implement this in {DT}. {DT} has built-in `selection = list(mode = "single", selected = c(...), target = "row")` to allow us to make rows selectable and update the selection. It would be easier to sort this out once and then keep using the same technique (almost definitely a single module that we then reuse).

**Comment by jonthegeek** [comment]
Try to implement this with gt, since that's what we're using everywhere else.
