### ISSUE TITLE
Bugfix: swap `Param` with `Label` on the Site Metadata card.

### ISSUE THREAD

**Issue by taylorrodgers** [Gilead-BioStats/gsm.app#191]
## Expected Behavior
Not really a bug per se, but we'd like to swap the Site Metadata below from `dfGroups` to use the new `Labels` column rather than the `Param` column. This will be a cleaner look for the card shown below.

The change will need to be made in `taglist_site_meta_data.R`.

![image](https://github.com/user-attachments/assets/cc8ff610-5aed-4eca-a8f5-e435a2aa0ba5)

This is waiting on: https://github.com/Gilead-BioStats/gsm/pull/1791

**Comment by jonthegeek** [comment]
This is ready to go. Do a check to see if Labels already exists, call `dfGroups <- gsm::MakeParamLabels(dfGroups)` if it doesn't.

**Comment by jonthegeek** [comment]
Closed via #206
