### ISSUE TITLE
QC: bslib cards

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.app#198]
## QC Details
Implement {bslib} throughout the package. Cards should be [bslib::card()](https://rstudio.github.io/bslib/articles/cards/index.html)s, for example.

## Additional Comments
I'm adding this ticket so I can feel ok not fixing everything as I go!

**Comment by jonthegeek** [comment]
Gilead's stylesheet is here: https://www.gilead.com/Areas/GileadCorporate/Content/dist/main.css?v=20240812121745
That's bs4. Provide a path to implement that (and things like it), including a spike to see if we can upgrade that ~easily to bs5.

**Comment by samussiah** [comment]
#r&d, nice find!
