### ISSUE TITLE
Feature: Sort table_participants_by_site by Metric value descending

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.app#201]
## Feature Details
As an app user, when I click a site, I'd like to see the worst cases at the top, so that I can drill down into those cases.

**Comment by taylorrodgers** [comment]
Will be on next PR. Posting screenshot here:
![image](https://github.com/user-attachments/assets/5ab2cc28-dfd2-4477-976d-778b69c071c6)
