### ISSUE TITLE
Feature: Params-to-Labels in Participant Metadata

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.app#204]
## Feature Details
Use `gsm::MakeParamLabelsList()` to make the labels in the Participant Metadata module prettier.

**Comment by taylorrodgers** [comment]
Site metadata:
![image](https://github.com/user-attachments/assets/a1f363c2-3609-4aa0-afda-44cc280ec9a0)

Participant cards:
![image](https://github.com/user-attachments/assets/5b84a8c3-cb0f-4090-9368-01f1378a3662)
