### ISSUE TITLE
UI: Adjustable column widths in drill-down tables

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm.app#224]
## UI Details

Allow users to adjust column widths in drill-down tables (or all tables) for improved readability of columns with text in cells.

**Comment by lauramaxwell** [comment]
yeah, i'll remove this issue from 2.0.

**Comment by jonthegeek** [comment]
This comes for ~free when we finish switching everything to {gt} (#289) 🎉
