### ISSUE TITLE
Feature: Add Site Details tab

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm.app#225]
## Feature Details

Show all participants (with or without a KRI) from a site in a view, similar to the participant details view, but with site-level aggregated information and all participants from the site listed in the drill down table. 

## Additional Comments

Will need to discuss the important metrics to display here and if UI is different than Participant Details.

**Comment by jonthegeek** [comment]
I was already thinking we should move the Site Details bits from the bottom of Metric Details onto their own "Site Details" tab... but the plan wasn't for that to be quite what they're talking about.

I *think* I agree with Jeremy's idea to 
1. Rename "Participant Details" to something more generic, like "Drill Down".
2. Show all the same stats (minus the patient info) even if they don't have a specific participant selected.

**Comment by jonthegeek** [comment]
Duplicated in #245.
